name: Unit Tests

on:
  pull_request:
    paths:
      - ".github/workflows/unit-tests.yml"
      - 'test/**'
      - 'src/**'

  push:
    paths:
      - ".github/workflows/unit-tests.yml"
      - 'test/**'
      - 'src/**'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      # cd to the build dir before run ctest
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -V
      
